# l10n.yaml
arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
untranslated-messages-file: missingTranslations.json
# Optional: if you want to specify the output class name
output-class: S
# Optional: if you want nullable getter (older projects might need this for migration)
# nullable-getter: false
# Optional: to specify a specific directory for the generated files
# output-dir: lib/generated/l10n
