# This is the main pubspec.yaml file
# The setup scripts will modify this file based on the selected flavor

name: teleferika
description: "TeleferiKa app."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+84

environment:
  sdk: '>=3.8.1 <4.0.0'
  flutter: ">=3.32.4"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  # Licensed features package (will be added/removed by setup scripts)
  # DO NOT REMOVE THE NEXT LINE!!!
  # LICENSED_PACKAGE_PLACEHOLDER
  licensed_features_package:
    path: ./licensed_features_package


  compassx: ^1.0.1
  crypto: ^3.0.6
  csv: ^6.0.0
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.5.0
  drift: ^2.27.0
  drift_flutter: ^0.2.4
  file_picker: ^10.2.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_map: ^8.2.1
  flutter_map_compass: ^1.1.1
  flutter_map_location_marker: ^10.1.0
  flutter_map_tile_caching: ^10.1.1
  geolocator: ^14.0.2
  http: ^1.5.0-beta.2
  image_picker: ^1.1.2
  intl: ^0.20.2
  latlong2: ^0.9.1
  logging: ^1.3.0
  lottie: ^3.3.1
  package_info_plus: ^8.3.0
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  pointycastle: ^4.0.0
  provider: ^6.1.2
  asn1lib: ^1.6.5
  reorderable_grid_view: ^2.2.8
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  sqlite3_flutter_libs: ^0.5.34
  sqflite: ^2.4.2
  url_launcher: ^6.3.2
  uuid: ^4.5.1
  xml: ^6.5.0
  
dev_dependencies:
  build_runner: ^2.5.4
  drift_dev: ^2.27.0
  flutter_lints: any #^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/animations/
