// project_details_page.dart
// ignore_for_file: curly_braces_in_flow_control_structures

import 'dart:math' as math;

import 'package:flutter/material.dart';
import 'package:geolocator/geolocator.dart';
import 'package:intl/intl.dart';
import 'package:teleferika/licensing/licence_service.dart';
import 'package:teleferika/project_tools/compass_tool_view.dart';
import 'package:teleferika/project_tools/map_tool_view.dart';
import 'package:teleferika/project_tools/points_tool_view.dart';

import 'db/database_helper.dart'; // Ensure correct path
import 'db/models/point_model.dart';
import 'db/models/project_model.dart'; // Ensure correct path
import 'export/export_page.dart';
import 'l10n/app_localizations.dart';
import 'logger.dart';

enum ProjectPageTab {
  details, // 0
  points, // 1
  compass, // 2
  map, // 3
  // Add more tabs here if needed
}

// Helper function to convert degrees to radians
double _degreesToRadians(double degrees) {
  return degrees * math.pi / 180.0;
}

// Helper function to convert radians to degrees
double _radiansToDegrees(double radians) {
  return radians * 180.0 / math.pi;
}

/// Calculates the initial bearing (azimuth) from a start point to an end point.
/// Returns the bearing in degrees (0-360).
double calculateBearingFromPoints(PointModel startPoint, PointModel endPoint) {
  final double lat1Rad = _degreesToRadians(startPoint.latitude);
  final double lon1Rad = _degreesToRadians(startPoint.longitude);
  final double lat2Rad = _degreesToRadians(endPoint.latitude);
  final double lon2Rad = _degreesToRadians(endPoint.longitude);

  final double dLon = lon2Rad - lon1Rad;

  final double y = math.sin(dLon) * math.cos(lat2Rad);
  final double x =
      math.cos(lat1Rad) * math.sin(lat2Rad) -
      math.sin(lat1Rad) * math.cos(lat2Rad) * math.cos(dLon);

  double bearingRad = math.atan2(y, x);
  double bearingDeg = _radiansToDegrees(bearingRad);

  // Normalize to 0-360 degrees
  return (bearingDeg + 360) % 360;
}

class ProjectPage extends StatefulWidget {
  final ProjectModel project;
  final bool isNew;

  const ProjectPage({super.key, required this.project, required this.isNew});

  @override
  State<ProjectPage> createState() => _ProjectPageState();
}

class _ProjectPageState extends State<ProjectPage> {
  final GlobalKey<FormState> _projectFormKey = GlobalKey<FormState>();
  final DatabaseHelper _dbHelper = DatabaseHelper.instance;

  late TextEditingController _nameController;
  late TextEditingController _noteController;
  late TextEditingController _azimuthController;

  late DateTime? _projectDate;
  late DateTime? _lastUpdateTime;

  late ProjectModel _currentProject;

  bool _isLoading = false;
  bool _hasUnsavedChanges = false;
  // State variable to manage if this instance is effectively new for saving behavior
  // This helps when saving a 'new' project and then immediately saving it again
  // without leaving the page.
  bool _isEffectivelyNew = true;

  // GlobalKey to access PointsToolView's state if needed for refresh
  // This is one way to trigger refresh. Another is to manage points list here.
  final GlobalKey<PointsToolViewState> _pointsToolViewKey =
      GlobalKey<PointsToolViewState>();
  final GlobalKey<ScaffoldState> _scaffoldKey = GlobalKey<ScaffoldState>();

  // State variable to control CompassToolView's spinner for this action
  bool _isAddingPointFromCompassInProgress = false;
  // ID of the most recently added point (for adding NEW icon)
  String? _newlyAddedPointId;
  bool _projectWasSuccessfullySaved = false;

  final LicenceService _licenceService =
      LicenceService.instance; // Get instance

  @override
  void initState() {
    super.initState();
    _currentProject = widget.project;
    _isEffectivelyNew = widget.isNew; // Initialize based on widget property

    _nameController = TextEditingController(text: _currentProject.name);
    _noteController = TextEditingController(text: _currentProject.note ?? '');
    _azimuthController = TextEditingController(
      text: _currentProject.azimuth?.toStringAsFixed(2) ?? '',
    );
    _projectDate =
        _currentProject.date ?? (widget.isNew ? DateTime.now() : null);
    _lastUpdateTime = _currentProject.lastUpdate;

    if (!widget.isNew) {
      // Only load if it's an existing project
      logger.info(
        "ProjectPage initialized for EXISTING project. ID: ${_currentProject.id}, Name: ${_currentProject.name}. Loading details...",
      );
      _loadProjectDetails();
    } else {
      logger.info(
        "ProjectDetailsPage initialized for a NEW project. Name: ${_currentProject.name}",
      );
      // For a new project, we are ready with the initial draft.
      // _currentProject.id is already generated by the model.
      // We know it's not in the DB because widget.isNew is true.
    }
  }

  void _onChanged() {
    if (!_hasUnsavedChanges) {
      setState(() {
        _hasUnsavedChanges = true;
      });
    }
  }

  Future<void> _checkLicenceAndProceedToExport() async {
    final s = S.of(context);
    bool licenceIsValid = await _licenceService.isLicenceValid();

    if (!licenceIsValid) {
      if (mounted) {
        showDialog(
          context: context,
          builder: (BuildContext dialogContext) {
            final dialogS = S.of(
              dialogContext,
            ); // Get S instance for dialog's context
            return AlertDialog(
              title: Text(
                dialogS?.export_requires_licence_title ?? "Licence Required",
              ),
              content: Text(
                dialogS?.export_requires_licence_message ??
                    "Exporting project data requires an active licence. Please import a valid licence.",
              ),
              actions: <Widget>[
                TextButton(
                  child: Text(dialogS?.dialog_cancel ?? 'Cancel'),
                  onPressed: () {
                    Navigator.of(dialogContext).pop();
                  },
                ),
                TextButton(
                  child: Text(
                    dialogS?.action_import_licence ?? 'Import Licence',
                  ),
                  onPressed: () async {
                    Navigator.of(dialogContext).pop(); // Close current dialog
                    // You might want to navigate to a dedicated licence page or trigger the import flow from here
                    // For simplicity, let's assume we can trigger the import flow similarly to ProjectsListPage
                    // This might involve passing a callback or navigating back to ProjectsListPage to handle it
                    // Or, call _licenceService.importLicenceFromFile() directly if UI context is suitable
                    // For now, let's just log and inform the user to do it from the main page
                    try {
                      final importedLicence = await _licenceService
                          .importLicenceFromFile();
                      if (mounted) {
                        if (importedLicence != null) {
                          ScaffoldMessenger.of(context).showSnackBar(
                            SnackBar(
                              content: Text(
                                'Licence for ${importedLicence.email} imported! Try exporting again.',
                              ),
                              backgroundColor: Colors.green,
                            ),
                          );
                        } else {
                          ScaffoldMessenger.of(context).showSnackBar(
                            const SnackBar(
                              content: Text(
                                'Licence import cancelled or failed.',
                              ),
                              backgroundColor: Colors.orange,
                            ),
                          );
                        }
                      }
                    } on FormatException catch (e) {
                      if (mounted) {
                        ScaffoldMessenger.of(context).showSnackBar(
                          SnackBar(
                            content: Text(e.message),
                            backgroundColor: Colors.red,
                          ),
                        );
                      }
                    } catch (e) {
                      if (mounted) {
                        ScaffoldMessenger.of(context).showSnackBar(
                          SnackBar(
                            content: Text(
                              'Error importing licence: $e. Please try from the main page.',
                            ),
                            backgroundColor: Colors.red,
                          ),
                        );
                      }
                    }
                  },
                ),
              ],
            );
          },
        );
      }
      return; // Stop export if licence is not valid
    }

    // If licence is valid, proceed to the actual export navigation
    _navigateToExportPage(); // Your existing method
  }

  void _switchToTab(ProjectPageTab tab) {
    if (!mounted) return;

    final BuildContext? scaffoldContext = _scaffoldKey.currentContext;

    if (scaffoldContext != null) {
      final TabController controller = DefaultTabController.of(scaffoldContext);
      final int tabIndex = tab.index;

      if (tabIndex >= 0 && controller.index != tabIndex) {
        controller.animateTo(tabIndex);
      }
    } else {
      logger.warning(
        "Scaffold key context is null, cannot switch tab. Widget might be unmounted or Scaffold not built yet.",
      );
    }
  }

  Future<void> _loadProjectDetails() async {
    setStateIfMounted(() => _isLoading = true);
    try {
      final projectDataFromDb = await _dbHelper.getProjectById(
        _currentProject.id,
      );
      if (projectDataFromDb != null && mounted) {
        setState(() {
          _currentProject = projectDataFromDb;

          _nameController.text = _currentProject.name;
          _noteController.text = _currentProject.note ?? '';
          _azimuthController.text =
              _currentProject.azimuth?.toStringAsFixed(2) ?? '';
          _projectDate = _currentProject.date;
          _lastUpdateTime = _currentProject.lastUpdate;
        });
      }
      logger.info(
        "Project details loaded/refreshed for ID: ${_currentProject.id}",
      );
    } catch (e, stackTrace) {
      logger.severe(
        "Error loading project details for ID ${_currentProject.id}",
        e,
        stackTrace,
      );
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(
              S.of(context)!.errorLoadingProjectDetails(e.toString()),
            ),
            backgroundColor: Colors.red,
          ),
        );
      }
    } finally {
      setStateIfMounted(() => _isLoading = false);
    }
  }

  @override
  void dispose() {
    _nameController.removeListener(_onChanged);
    _noteController.removeListener(_onChanged);
    _azimuthController.removeListener(_onChanged);

    _nameController.dispose();
    _noteController.dispose();
    _azimuthController.dispose();
    super.dispose();
  }

  // --- Logic for Adding Point from Compass ---
  Future<Position> _determinePosition() async {
    bool serviceEnabled;
    LocationPermission permission;

    serviceEnabled = await Geolocator.isLocationServiceEnabled();
    if (!serviceEnabled) {
      logger.warning('Location services are disabled.');
      throw Exception('Location services are disabled.');
    }

    permission = await Geolocator.checkPermission();
    if (permission == LocationPermission.denied) {
      permission = await Geolocator.requestPermission();
      if (permission == LocationPermission.denied) {
        logger.warning('Location permissions are denied.');
        throw Exception('Location permissions are denied');
      }
    }

    if (permission == LocationPermission.deniedForever) {
      logger.warning(
        'Location permissions are permanently denied, we cannot request permissions.',
      );
      throw Exception(
        'Location permissions are permanently denied, we cannot request permissions.',
      );
    }
    return await Geolocator.getCurrentPosition();
  }

  Future<int> _getNextOrdinalNumber(String projectId) async {
    final lastOrdinal = await _dbHelper.getLastPointOrdinal(projectId);
    return (lastOrdinal ?? -1) + 1; // If no points, next ordinal is 0
  }

  Future<void> _initiateAddPointFromCompass(
    BuildContext descendantContext,
    double heading, {
    bool? setAsEndPoint, // Added optional named parameter
  }) async {
    final bool addAsEndPoint =
        setAsEndPoint ?? false; // Default to false if null

    logger.info(
      "Initiating add point. Heading: $heading, Project ID: ${_currentProject.id}, Explicit End Point: $setAsEndPoint",
    );

    // START loading indicator in CompassToolView by setting state
    if (mounted) {
      setState(() {
        _isAddingPointFromCompassInProgress = true;
      });
    }

    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text(S.of(context)!.infoFetchingLocation),
        duration: const Duration(seconds: 2), // Short duration
      ),
    );

    PointModel? currentEndPointModel;
    int? originalEndPointOrdinal;
    int
    newPointOrdinal; // This will be the ordinal for the point being added from compass

    try {
      final position = await _determinePosition();
      // final nextOrdinal = await _getNextOrdinalNumber(_currentProject.id!);
      if (!addAsEndPoint && _currentProject.endingPointId != null) {
        // --- Case 1: NOT setting as new end point, AND an old end point exists ---
        currentEndPointModel = await _dbHelper.getPointById(
          _currentProject.endingPointId!,
        );

        if (currentEndPointModel != null) {
          originalEndPointOrdinal = currentEndPointModel.ordinalNumber;
          // The new point from compass will take the original end point's ordinal
          newPointOrdinal = originalEndPointOrdinal;

          // The OLD end point needs a new, higher ordinal
          final int newOrdinalForOldEndPoint = await _getNextOrdinalNumber(
            _currentProject.id,
          );

          PointModel updatedOldEndPoint = currentEndPointModel.copyWith(
            ordinalNumber: newOrdinalForOldEndPoint,
          );
          await _dbHelper.updatePoint(updatedOldEndPoint);
          logger.info(
            "Old end point (ID: ${currentEndPointModel.id})'s ordinal shifted from $originalEndPointOrdinal to $newOrdinalForOldEndPoint.",
          );
        } else {
          // Fallback if currentProject.endingPointId was set but point not found (data integrity issue)
          logger.warning(
            "Project's endingPointId ${_currentProject.endingPointId} not found in DB. Proceeding as if no end point.",
          );
          newPointOrdinal = await _getNextOrdinalNumber(_currentProject.id);
        }
      } else {
        // --- Case 2: Setting as new end point OR no existing end point to shuffle ---
        newPointOrdinal = await _getNextOrdinalNumber(_currentProject.id);
      }

      final pointFromCompass = PointModel(
        projectId: _currentProject.id,
        latitude: position.latitude,
        longitude: position.longitude,
        altitude: position.altitude,
        ordinalNumber: newPointOrdinal,
        // You might want a default note or a way to add one later
        note: S
            .of(context)!
            .pointFromCompassDefaultNote(heading.toStringAsFixed(1)),
      );

      final newPointIdFromCompass = await _dbHelper.insertPoint(
        pointFromCompass,
      );
      logger.info(
        'Point added via Compass: ID $newPointIdFromCompass, Lat: ${position.longitude}, Lon: ${position.longitude}, Heading used for note: $heading, Ordinal: ${pointFromCompass.ordinalNumber}',
      );

      // AFTER point is inserted, update the project's start/end points
      if (addAsEndPoint) {
        // Update the project's endingPointId with the newPointIdFromCompass
        // Create a copy of _currentProject to modify its endingPointId
        ProjectModel projectToUpdate = _currentProject.copyWith(
          endingPointId: newPointIdFromCompass,
        );
        await _dbHelper.updateProject(projectToUpdate);
        logger.info(
          "New point ID $newPointIdFromCompass set as the END point for project ${_currentProject.id}.",
        );
      }
      // If !addAsExplicitEndPoint, _currentProject.endingPointId remains unchanged,
      // pointing to the ID of the original end point (which now has a new ordinal).

      // This method should now correctly identify start and end points based on their IDs
      // and potentially their ordinals (if it falls back to highest ordinal for end point if not set).
      await _dbHelper.updateProjectStartEndPoints(_currentProject.id!);
      await _loadProjectDetails(); // Reload project to get updated start/end IDs for the UI

      if (mounted) {
        setState(() {
          _newlyAddedPointId = newPointIdFromCompass;
        });
        ScaffoldMessenger.of(
          context,
        ).removeCurrentSnackBar(); // Remove "Fetching location..."
        String baseMessage = S
            .of(context)!
            .pointAddedSnackbar(pointFromCompass.ordinalNumber.toString());
        String suffix = "";
        if (addAsEndPoint == true) {
          // Explicitly check for true if addAsEndPoint is bool?
          suffix = " ${S.of(context)!.pointAddedSetAsEndSnackbarSuffix}";
        } else if (currentEndPointModel != null) {
          suffix =
              " ${S.of(context)!.pointAddedInsertedBeforeEndSnackbarSuffix}";
        }
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(baseMessage + suffix),
            backgroundColor: Colors.green,
          ),
        );
      }

      // Refresh PointsToolView if it's active or if you always want it updated
      _pointsToolViewKey.currentState
          ?.refreshPoints(); // Call refreshPoints on PointsToolView

      // If the compass tool is active, and you want to switch to points view
      _switchToTab(ProjectPageTab.points);
    } catch (e, stackTrace) {
      logger.severe("Error adding point from compass", e, stackTrace);
      if (mounted) {
        ScaffoldMessenger.of(context).removeCurrentSnackBar();
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(S.of(context)!.errorAddingPoint(e.toString())),
            backgroundColor: Colors.red,
          ),
        );
      }
    } finally {
      // STOP loading indicator in CompassToolView
      if (mounted) {
        setState(() {
          _isAddingPointFromCompassInProgress = false;
        });
      }
    }
  }
  // --- End Logic for Adding Point ---

  void setStateIfMounted(VoidCallback fn) {
    if (mounted) {
      setState(fn);
    }
  }

  Future<void> _selectProjectDate(BuildContext context) async {
    final DateTime? pickedDate = await showDatePicker(
      context: context,
      initialDate: _projectDate ?? DateTime.now(),
      firstDate: DateTime(1900),
      lastDate: DateTime(2101),
    );

    if (pickedDate != null && pickedDate != _projectDate) {
      setStateIfMounted(() {
        _projectDate = pickedDate;
        _hasUnsavedChanges = true;
      });
    }
  }

  Future<void> _calculateAzimuth() async {
    logger.info(
      "Calculate Azimuth button tapped for project: ${_currentProject.name}",
    );

    final String? startPointId = _currentProject.startingPointId;
    final String? endPointId = _currentProject.endingPointId;

    if (startPointId == null || endPointId == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(S.of(context)!.errorAzimuthPointsNotSet),
          backgroundColor: Colors.orange,
        ),
      );
      setStateIfMounted(() {
        _azimuthController.text = '';
        _currentProject = _currentProject.copyWith(
          azimuth: null,
          clearAzimuth: true,
        );
      });
      return;
    }

    if (startPointId == endPointId) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(S.of(context)!.errorAzimuthPointsSame),
          backgroundColor: Colors.orange,
        ),
      );
      setStateIfMounted(() {
        _azimuthController.text = '';
        _currentProject = _currentProject.copyWith(
          azimuth: null,
          clearAzimuth: true,
        );
      });
      return;
    }

    try {
      final PointModel? startPoint = await _dbHelper.getPointById(startPointId);
      final PointModel? endPoint = await _dbHelper.getPointById(endPointId);

      if (startPoint == null || endPoint == null) {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text(S.of(context)!.errorAzimuthCouldNotRetrievePoints),
              backgroundColor: Colors.red,
            ),
          );
        }
        logger.severe(
          "Error calculating azimuth: StartPoint (ID $startPointId) or EndPoint (ID $endPointId) not found.",
        );
        return;
      }

      final double calculatedAzimuth = calculateBearingFromPoints(
        startPoint,
        endPoint,
      );

      setStateIfMounted(() {
        _azimuthController.text = calculatedAzimuth.toStringAsFixed(2);
        // Update the project's azimuth
        _currentProject = _currentProject.copyWith(azimuth: calculatedAzimuth);
      });

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(
              S
                  .of(context)!
                  .azimuthCalculatedSnackbar(
                    calculatedAzimuth.toStringAsFixed(2),
                  ),
            ),
            backgroundColor: Colors.green,
          ),
        );
      }
      logger.info(
        "Azimuth calculated successfully: ${calculatedAzimuth.toStringAsFixed(2)}° from P${startPoint.ordinalNumber} to P${endPoint.ordinalNumber}",
      );
    } catch (e, stackTrace) {
      logger.severe("Error during azimuth calculation: $e", e, stackTrace);
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(S.of(context)!.errorCalculatingAzimuth(e.toString())),
            backgroundColor: Colors.red,
          ),
        );
      }
    }
  }

  Future<bool?> _saveProject() async {
    if (_isLoading) return null;

    if (_projectFormKey.currentState?.validate() ?? false) {
      _projectFormKey.currentState!.save();
      setState(() => _isLoading = true);

      // Create a new Project instance with the updated values
      ProjectModel projectToSave = _currentProject.copyWith(
        id: _currentProject.id,
        name: _nameController.text.trim(),
        date: _projectDate,
        note: _noteController.text.trim().isEmpty
            ? null
            : _noteController.text.trim(),
        lastUpdate:
            DateTime.now(), // DB helper also sets this, but good to have current here.
        startingPointId: _currentProject.startingPointId,
        endingPointId: _currentProject.endingPointId,
        azimuth: double.tryParse(_azimuthController.text),
      );

      try {
        if (_isEffectivelyNew) {
          String newId = await _dbHelper.insertProject(projectToSave);
          if (mounted) {
            // Update _currentProject to reflect the saved state (especially lastUpdate from DB if different)
            // For now, projectToSave is good enough.
            _currentProject = projectToSave.copyWith(
              id: newId, // FIXME: no need.. id does not change.. remove
            ); // Ensure ID consistency if DB generated it differently (not for UUIDs)
            // For client-generated UUIDs, projectToSave.id is already the ID.
            ScaffoldMessenger.of(context).showSnackBar(
              const SnackBar(
                content: Text('Project created successfully!'),
                backgroundColor: Colors.green,
              ),
            );
            _hasUnsavedChanges = false;
            _isEffectivelyNew =
                false; // It's no longer 'new' for this page instance
            _projectWasSuccessfullySaved = true;
            // Navigator.of(
            //   context,
            // ).pop({'action': 'saved', 'id': _currentProject.id!});
            // TODO: For now, we stay on the page, and subsequent saves will be updates.
            setState(
              () {},
            ); // To refresh display with new ID/lastUpdate if needed
          }
        } else {
          // For an existing project, update it
          int updatedRows = await _dbHelper.updateProject(projectToSave);
          if (updatedRows > 0) {
            _currentProject = projectToSave;
            _lastUpdateTime = _currentProject.lastUpdate;
            if (mounted) {
              ScaffoldMessenger.of(context).showSnackBar(
                const SnackBar(
                  content: Text('Project saved successfully!'),
                  backgroundColor: Colors.green,
                ),
              );
              _hasUnsavedChanges = false;
              _projectWasSuccessfullySaved = true;
              setState(() {}); // To refresh display of lastUpdate
              // TODO: or should we pop?
              // Navigator.of(
              //   context,
              // ).pop({'action': 'saved', 'id': _currentProject.id!});
            }
          } else {
            if (mounted) {
              ScaffoldMessenger.of(context).showSnackBar(
                const SnackBar(
                  content: Text('Project already up to date or not found.'),
                  backgroundColor: Colors.orangeAccent,
                ),
              );
            }
          }
        }
      } catch (e, stackTrace) {
        logger.severe("Error saving project: $e", e, stackTrace);
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text('Error saving project: ${e.toString()}'),
              backgroundColor: Colors.red,
            ),
          );
        }
      } finally {
        if (mounted) {
          setState(() {
            _isLoading = false;
          });
        }
      }
    } else {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Please correct the errors in the form.'),
          backgroundColor: Colors.orange,
        ),
      );
    }
    return _projectWasSuccessfullySaved;
  }

  Future<void> _confirmDeleteProject() async {
    if (_isEffectivelyNew || _currentProject.id == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Cannot delete a project that has not been saved yet.'),
          backgroundColor: Colors.orange,
        ),
      );
      return;
    }

    final bool? confirmed = await showDialog<bool>(
      context: context,
      builder: (BuildContext context) {
        return AlertDialog(
          title: const Text('Confirm Delete'),
          content: Text(
            'Are you sure you want to delete the project "${_currentProject.name}"? This action cannot be undone.',
          ),
          actions: <Widget>[
            TextButton(
              child: const Text('Cancel'),
              onPressed: () {
                Navigator.of(context).pop(false); // User canceled
              },
            ),
            TextButton(
              child: Text(
                'Delete',
                style: TextStyle(color: Theme.of(context).colorScheme.error),
              ),
              onPressed: () {
                Navigator.of(context).pop(true); // User confirmed
              },
            ),
          ],
        );
      },
    );

    if (confirmed == true) {
      if (_isLoading) return; // Prevent multiple delete attempts
      setState(() {
        _isLoading = true;
      });

      try {
        int deletedRows = await _dbHelper.deleteProject(_currentProject.id!);
        if (deletedRows > 0) {
          if (mounted) {
            ScaffoldMessenger.of(context).showSnackBar(
              const SnackBar(
                content: Text('Project deleted successfully.'),
                backgroundColor: Colors.green,
              ),
            );
            Navigator.of(
              context,
            ).pop({'action': 'deleted', 'id': _currentProject.id!});
          }
        } else {
          // This case might indicate the project was already deleted or not found
          if (mounted) {
            ScaffoldMessenger.of(context).showSnackBar(
              const SnackBar(
                content: Text('Project not found or already deleted.'),
                backgroundColor: Colors.orangeAccent,
              ),
            );
          }
        }
      } catch (e, stackTrace) {
        logger.severe("Error deleting project: $e", e, stackTrace);
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text('Error deleting project: ${e.toString()}'),
              backgroundColor: Colors.red,
            ),
          );
        }
      } finally {
        if (mounted) {
          setState(() {
            _isLoading = false;
          });
        }
      }
    }
  }

  void _navigateToExportPage() {
    // Get the S instance for localization
    final s = S.of(context);
    if (s == null) {
      // This should ideally not happen if localizations are set up correctly.
      // Fallback or log an error.
      logger.warning(
        "S.of(context) is null in _navigateToExportPage. Using default strings.",
      );
      // As a minimal fallback, you might proceed without localized strings,
      // or show an error and prevent navigation.
      // For this example, we'll use hardcoded defaults if 's' is null,
      // but in a real app, you'd want a more robust fallback.
    }

    if (_currentProject != null) {
      if (_hasUnsavedChanges && !_isEffectivelyNew) {
        showDialog(
          context: context,
          builder: (BuildContext dialogContext) {
            // Use dialogContext
            final dialogS = S.of(
              dialogContext,
            ); // Get S instance for dialog's context

            return AlertDialog(
              title: Text(dialogS?.unsaved_changes_title ?? 'Unsaved Changes'),
              content: Text(
                dialogS?.unsaved_changes_export_message ??
                    'You have unsaved changes. Please save the project before exporting to ensure all data is included.',
              ),
              actions: <Widget>[
                TextButton(
                  child: Text(dialogS?.dialog_cancel ?? 'Cancel'),
                  onPressed: () {
                    Navigator.of(dialogContext).pop();
                  },
                ),
                TextButton(
                  child: Text(dialogS?.save_button_label ?? 'Save'),
                  onPressed: () async {
                    Navigator.of(dialogContext).pop(); // Close the dialog first
                    bool saved = await _saveProject() ?? false;
                    if (saved && mounted) {
                      // Check 'mounted' again after async operation
                      Navigator.push(
                        context, // Use the original page context for navigation
                        MaterialPageRoute(
                          builder: (context) =>
                              ExportPage(project: _currentProject),
                        ),
                      );
                    }
                  },
                ),
              ],
            );
          },
        );
      } else if (_currentProject!.id.isEmpty && _isEffectivelyNew) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(
              s?.please_save_project_first_to_export ??
                  'Please save the new project first to enable export.',
            ),
          ),
        );
      } else {
        // Proceed to export page if no unsaved changes for an existing project,
        // or if it's a new project that's already been saved (has an ID).
        Navigator.push(
          context,
          MaterialPageRoute(
            builder: (context) => ExportPage(project: _currentProject!),
          ),
        );
      }
    } else {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(
            s?.project_not_loaded_cannot_export ??
                'Project not loaded. Cannot export data.',
          ),
        ),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    final s = S.of(context); // Get S instance for localizations
    if (s == null) {
      logger.warning(
        "S.of(context) is null in ProjectPage build. UI may not be localized.",
      );
      // Handle fallback if necessary, or proceed with default strings in tooltips/text
    }

    String formattedProjectDate;
    if (_projectDate != null) {
      // Use a common, locale-aware skeleton.
      // yMMMd() is a good general purpose format (e.g., "Sep 10, 2023" or "10 Sep 2023")
      // You can explore other skeletons like:
      // DateFormat.yMd(Localizations.localeOf(context).toString()).format(_projectDate!)
      // DateFormat.yMEd(Localizations.localeOf(context).toString()).format(_projectDate!) // Includes day of week
      // DateFormat.MMMMEEEEd(Localizations.localeOf(context).toString()).format(_projectDate!) // Very verbose

      // Get the current locale from the context
      final locale = Localizations.localeOf(context).toString();
      formattedProjectDate = DateFormat.yMMMd(locale).format(_projectDate!);
    } else {
      formattedProjectDate = 'Tap to set date';
    }
    String formattedLastUpdate = _lastUpdateTime != null
        ? DateFormat.yMMMd(
            Localizations.localeOf(context).toString(),
          ).add_Hm().format(_lastUpdateTime!) // Also localize time
        : 'Not yet saved';

    // Determine the title based on whether it's a new project or editing an existing one
    String appBarTitle;
    if (_isEffectivelyNew) {
      appBarTitle = 'New Project';
    } else {
      // Assuming 'edit_project_title' is a key in your ARB file.
      // You might want a different key if the project name is part of the title.
      // For example: "edit_project_title_named": "Edit: {projectName}"
      // Then: s.edit_project_title_named(_currentProject?.name ?? '')
      appBarTitle = _currentProject.name;
    }

    // For the TabBar, you'll need a TabController.
    // The easiest way is to wrap your Scaffold with DefaultTabController.
    return DefaultTabController(
      length: ProjectPageTab.values.length, // Number of tabs
      child: Scaffold(
        key: _scaffoldKey,
        appBar: AppBar(
          title: Text(appBarTitle),
          actions: [
            if (!_isEffectivelyNew) // Show delete only for existing projects
              IconButton(
                icon: const Icon(Icons.delete_outline, color: Colors.redAccent),
                onPressed: _isLoading ? null : _confirmDeleteProject,
                tooltip: 'Delete Project',
              ),
            if (!_isEffectivelyNew)
              IconButton(
                icon: const Icon(
                  Icons.output,
                ), // Or Icons.ios_share, Icons.file_upload
                // Using the localized string for the tooltip
                tooltip:
                    s?.export_project_data_tooltip ?? 'Export Project Data',
                onPressed: (_isEffectivelyNew || _isLoading)
                    ? null // Disable if project is new and never saved, or if loading
                    : _checkLicenceAndProceedToExport,
              ),
            IconButton(
              icon: Icon(_hasUnsavedChanges ? Icons.save : Icons.save_outlined),
              onPressed: _isLoading ? null : _saveProject,
              tooltip: 'Save Project',
              color: _hasUnsavedChanges
                  ? Theme.of(context).colorScheme.primary
                  : null,
            ),
          ],
          bottom: const TabBar(
            isScrollable:
                false, // Set to true if you have many tabs that don't fit
            tabs: [
              Tab(icon: Icon(Icons.info_outline), text: "Details"),
              Tab(
                icon: Icon(Icons.list_alt_outlined),
                text: "Points",
              ), // Changed icon for variety
              Tab(icon: Icon(Icons.explore_outlined), text: "Compass"),
              Tab(icon: Icon(Icons.map_outlined), text: "Map"),
            ],
          ),
        ),
        body: PopScope(
          // Use PopScope for "are you sure you want to leave" dialog
          canPop: false,
          onPopInvokedWithResult: (bool didPop, Object? result) async {
            if (didPop) {
              return;
            }
            if (_hasUnsavedChanges) {
              final bool? shouldPop = await showDialog<bool>(
                context: context,
                builder: (context) => AlertDialog(
                  title: const Text('Unsaved Changes'),
                  content: const Text(
                    'You have unsaved changes. Do you want to discard them and leave?',
                  ),
                  actions: [
                    TextButton(
                      child: const Text('Cancel'),
                      onPressed: () => Navigator.of(context).pop(false),
                    ),
                    TextButton(
                      child: const Text('Discard'),
                      onPressed: () => Navigator.of(context).pop(true),
                    ),
                  ],
                ),
              );
              if (shouldPop == true) {
                // ignore: use_build_context_synchronously
                if (mounted) Navigator.of(context).pop();
              }
            } else {
              // No unsaved changes, so we can pop.
              // Now check if a save occurred at any point.
              if (mounted) {
                if (_projectWasSuccessfullySaved) {
                  Navigator.of(context).pop<Map<String, dynamic>>({
                    'action': 'saved', // Or 'saved_and_exited'
                    'id': _currentProject.id, // Pass the latest saved state
                  });
                } else {
                  // No unsaved changes, and no save occurred during this page's lifetime
                  Navigator.of(
                    context,
                  ).pop(); //({'action': 'no_changes_made'}); // Or simply pop() for null
                }
              }
            }
          },
          child: TabBarView(
            children: [
              // Tab 1: Project Details Form
              SingleChildScrollView(
                padding: const EdgeInsets.all(16.0),
                child: Form(
                  key: _projectFormKey,
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.stretch,
                    children: <Widget>[
                      _buildTextFormField(
                        controller: _nameController,
                        label: 'Project Name',
                        validator: (value) {
                          if (value == null || value.trim().isEmpty) {
                            return S
                                .of(context)!
                                .projectNameCannotBeEmptyValidator;
                          }
                          return null;
                        },
                      ),
                      const SizedBox(height: 8),
                      InkWell(
                        onTap: () => _selectProjectDate(context),
                        child: InputDecorator(
                          decoration: InputDecoration(
                            labelText: S.of(context)!.formFieldProjectDateLabel,
                            border: const OutlineInputBorder(),
                          ),
                          child: Text(formattedProjectDate),
                        ),
                      ),
                      const SizedBox(height: 8),
                      _buildTextFormField(
                        controller: _noteController,
                        label: S.of(context)!.formFieldNoteLabel,
                        maxLines: 3,
                      ),
                      const SizedBox(height: 8),
                      Row(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Expanded(
                            child: _buildTextFormField(
                              controller: _azimuthController,
                              label: S.of(context)!.formFieldAzimuthLabel,
                              keyboardType:
                                  const TextInputType.numberWithOptions(
                                    decimal: true,
                                    signed: true,
                                  ),
                              validator: (value) {
                                if (value != null && value.trim().isNotEmpty) {
                                  final num = double.tryParse(value.trim());
                                  if (num == null) return 'Invalid number.';
                                  if (num <= -360 || num >= 360)
                                    return 'Must be +/-359.99';
                                }
                                return null;
                              },
                            ),
                          ),
                          const SizedBox(width: 10),
                          Padding(
                            padding: const EdgeInsets.only(top: 8.0),
                            child: ElevatedButton(
                              onPressed: _calculateAzimuth,
                              style: ElevatedButton.styleFrom(
                                padding: const EdgeInsets.symmetric(
                                  horizontal: 12,
                                  vertical: 12,
                                ),
                              ),
                              child: Text(S.of(context)!.buttonCalculate),
                            ),
                          ),
                        ],
                      ),
                      const SizedBox(height: 16),
                      if (!_isEffectivelyNew && _lastUpdateTime != null)
                        Padding(
                          padding: const EdgeInsets.symmetric(vertical: 8.0),
                          child: Text(
                            'Last updated: $formattedLastUpdate',
                            style: Theme.of(context).textTheme.bodySmall,
                            textAlign: TextAlign.center,
                          ),
                        ),
                      // Add other relevant UI elements from your original design
                    ],
                  ),
                ),
              ),
              // Tab 2: Points
              PointsToolView(
                key: _pointsToolViewKey, // Assign the GlobalKey
                project: _currentProject,
                onPointsChanged: _onPointsChanged,
                newlyAddedPointId: _newlyAddedPointId,
              ),

              // Tab 3: Compass
              // You might need to pass project data or specific settings
              CompassToolView(
                project: _currentProject,
                onAddPointFromCompass:
                    _initiateAddPointFromCompass, // Pass the callback
                isAddingPoint: _isAddingPointFromCompassInProgress,
              ),

              // Tab 4: Map
              // Pass the current project. MapToolView will handle loading its points.
              Center(
                child: SizedBox(
                  height:
                      MediaQuery.of(context).size.height *
                      0.7, // e.g., 60% of screen height
                  child: MapToolView(project: _currentProject),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  void _onPointsChanged() async {
    logger.info(
      "ProjectDetailsPage: Points changed, reloading project details.",
    );
    await _loadProjectDetails(); // Reload project details to get new start/end IDs
    _pointsToolViewKey.currentState
        ?.refreshPoints(); // Ensure PointsToolView itself also refreshes its internal list
  }

  Widget _buildTextFormField({
    required TextEditingController controller,
    required String label,
    int maxLines = 1,
    TextInputType? keyboardType,
    String? Function(String?)? validator,
    AutovalidateMode autovalidateMode = AutovalidateMode.onUserInteraction,
    bool readOnly = false,
    Widget? suffixIcon,
    VoidCallback? onTap,
  }) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 8.0),
      child: TextFormField(
        controller: controller,
        decoration: InputDecoration(
          labelText: label,
          border: const OutlineInputBorder(),
          suffixIcon: suffixIcon,
          // contentPadding: const EdgeInsets.symmetric(
          //   horizontal: 14.0,
          //   vertical: 18.0,
          // ),
        ),
        style: const TextStyle(fontSize: 18.0),
        maxLines: maxLines,
        keyboardType: keyboardType,
        validator: validator,
        autovalidateMode: autovalidateMode,
        readOnly: readOnly,
        onTap: onTap,
      ),
    );
  }
}
